directory: 'D:/CRPT/2021.08_август/расхождения/combined/' # ,без слеша на конце
sheet_name: 'Sheet1'
notNANcolumnsList: ['GTIN']
outputDirectory:  'D:/CRPT/2021.08_август/расхождения/combined/concatinated/'
outputFile: 'concatinated.xlsx'
log: 'log.xlsx'