directory: 'D:/CRPT/2021.05_май/внесение изменений/загруженые файлы импорты/Молочная продукция'
sheet_name: 'Лист1'
notNANcolumnsList: ['GTIN']
outputDirectory: 'D:/CRPT/2021.05_май/внесение изменений/загруженые файлы импорты/Молочная продукция/concatinated'
outputFile: 'concatinated.xlsx'
log: 'log.xlsx'